name: Build and deploy to Azure Container Apps

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  ACR_NAME: adlaboacr26hack
  APP_RESOURCE_GROUP: AdLabo

  WEB_CONTAINER_APP_NAME: agent-hack-trial
  WORKER_CONTAINER_APP_NAME: agent-hack-trial-worker

  WEB_IMAGE_NAME: 26-agent-hack-trial
  WORKER_IMAGE_NAME: 26-agent-hack-trial-worker

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Build and deploy Web Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}
          dockerfilePath: Dockerfile
          acrName: ${{ env.ACR_NAME }}
          containerAppName: ${{ env.WEB_CONTAINER_APP_NAME }}
          resourceGroup: ${{ env.APP_RESOURCE_GROUP }}
          imageToBuild: ${{ env.ACR_NAME }}.azurecr.io/${{ env.WEB_IMAGE_NAME }}:${{ github.sha }}

      - name: Build and deploy Worker Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}
          dockerfilePath: Dockerfile.worker
          acrName: ${{ env.ACR_NAME }}
          containerAppName: ${{ env.WORKER_CONTAINER_APP_NAME }}
          resourceGroup: ${{ env.APP_RESOURCE_GROUP }}
          imageToBuild: ${{ env.ACR_NAME }}.azurecr.io/${{ env.WORKER_IMAGE_NAME }}:${{ github.sha }}